[package]
name = "Pillager-Bot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenv = "0.15.0"
poise = "0.6.1"
regex = "1.10.5"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio-rustls", "chrono"] }
tokio = { version = "1.38.0", features = ["full"] }
